name: m3k
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  go_router: ^8.0.5
  flutter_svg: ^2.0.5
  http: ^0.13.6
  loading_indicator: ^3.1.0
  fluttertoast: ^8.2.2
  easy_localization: ^3.0.1
  flutter_bloc: ^8.1.2
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^13.0.0
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.3
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^7.4.0
  group_button: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/user/
    - assets/translations/

  fonts:
    - family: Somar
      fonts:
        - asset: assets/font/Somar-Regular.otf




